version: "3.8"

services: 
    db:
        image: postgres:latest
        container_name: postgresdb_quarkus
        environment:
            # MARIADB_ROOT_PASSWORD: developer
            # MARIADB_DATABASE: fruit
            # MARIADB_USER: developer
            # MARIADB_PASSWORD: developer
            POSTGRES_PASSWORD: production
            POSTGRES_USER: production
            POSTGRES_DB: fruitsdb

        ports:
            - 3000:5432
        networks:
            backend: 
                aliases: 
                    - db
    api:
        build:
            context: .
            dockerfile: ./src/main/docker/Dockerfile.jvm
        image: fruits:prod
        container_name: fruits-api-prod
        depends_on: 
            - db
        ports: 
            - 8080:8080
        networks: 
            - backend

networks:
    backend:
        name: network-backend
        driver: bridge